/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ak.svg -e ../../StateFlags.bundle/ak@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ak.svg -e ../../StateFlags.bundle/ak.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f al.svg -e ../../StateFlags.bundle/al@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f al.svg -e ../../StateFlags.bundle/al.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ar.svg -e ../../StateFlags.bundle/ar@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ar.svg -e ../../StateFlags.bundle/ar.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f az.svg -e ../../StateFlags.bundle/az@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f az.svg -e ../../StateFlags.bundle/az.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ca.svg -e ../../StateFlags.bundle/ca@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ca.svg -e ../../StateFlags.bundle/ca.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f co.svg -e ../../StateFlags.bundle/co@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f co.svg -e ../../StateFlags.bundle/co.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ct.svg -e ../../StateFlags.bundle/ct@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ct.svg -e ../../StateFlags.bundle/ct.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f dc.svg -e ../../StateFlags.bundle/dc@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f dc.svg -e ../../StateFlags.bundle/dc.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f de.svg -e ../../StateFlags.bundle/de@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f de.svg -e ../../StateFlags.bundle/de.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f fl.svg -e ../../StateFlags.bundle/fl@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f fl.svg -e ../../StateFlags.bundle/fl.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ga.svg -e ../../StateFlags.bundle/ga@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ga.svg -e ../../StateFlags.bundle/ga.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f hi.svg -e ../../StateFlags.bundle/hi@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f hi.svg -e ../../StateFlags.bundle/hi.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ia.svg -e ../../StateFlags.bundle/ia@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ia.svg -e ../../StateFlags.bundle/ia.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f id.svg -e ../../StateFlags.bundle/id@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f id.svg -e ../../StateFlags.bundle/id.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f il.svg -e ../../StateFlags.bundle/il@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f il.svg -e ../../StateFlags.bundle/il.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f in.svg -e ../../StateFlags.bundle/in@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f in.svg -e ../../StateFlags.bundle/in.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ks.svg -e ../../StateFlags.bundle/ks@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ks.svg -e ../../StateFlags.bundle/ks.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ky.svg -e ../../StateFlags.bundle/ky@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ky.svg -e ../../StateFlags.bundle/ky.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f la.svg -e ../../StateFlags.bundle/la@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f la.svg -e ../../StateFlags.bundle/la.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ma.svg -e ../../StateFlags.bundle/ma@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ma.svg -e ../../StateFlags.bundle/ma.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f md.svg -e ../../StateFlags.bundle/md@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f md.svg -e ../../StateFlags.bundle/md.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f me.svg -e ../../StateFlags.bundle/me@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f me.svg -e ../../StateFlags.bundle/me.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mi.svg -e ../../StateFlags.bundle/mi@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mi.svg -e ../../StateFlags.bundle/mi.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mn.svg -e ../../StateFlags.bundle/mn@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mn.svg -e ../../StateFlags.bundle/mn.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mo.svg -e ../../StateFlags.bundle/mo@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mo.svg -e ../../StateFlags.bundle/mo.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ms.svg -e ../../StateFlags.bundle/ms@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ms.svg -e ../../StateFlags.bundle/ms.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mt.svg -e ../../StateFlags.bundle/mt@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f mt.svg -e ../../StateFlags.bundle/mt.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nc.svg -e ../../StateFlags.bundle/nc@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nc.svg -e ../../StateFlags.bundle/nc.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nd.svg -e ../../StateFlags.bundle/nd@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nd.svg -e ../../StateFlags.bundle/nd.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ne.svg -e ../../StateFlags.bundle/ne@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ne.svg -e ../../StateFlags.bundle/ne.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nh.svg -e ../../StateFlags.bundle/nh@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nh.svg -e ../../StateFlags.bundle/nh.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nj.svg -e ../../StateFlags.bundle/nj@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nj.svg -e ../../StateFlags.bundle/nj.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nm.svg -e ../../StateFlags.bundle/nm@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nm.svg -e ../../StateFlags.bundle/nm.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nv.svg -e ../../StateFlags.bundle/nv@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f nv.svg -e ../../StateFlags.bundle/nv.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ny.svg -e ../../StateFlags.bundle/ny@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ny.svg -e ../../StateFlags.bundle/ny.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f oh.svg -e ../../StateFlags.bundle/oh@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f oh.svg -e ../../StateFlags.bundle/oh.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ok.svg -e ../../StateFlags.bundle/ok@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ok.svg -e ../../StateFlags.bundle/ok.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f or.svg -e ../../StateFlags.bundle/or@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f or.svg -e ../../StateFlags.bundle/or.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f pa.svg -e ../../StateFlags.bundle/pa@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f pa.svg -e ../../StateFlags.bundle/pa.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f pr.svg -e ../../StateFlags.bundle/pr@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f pr.svg -e ../../StateFlags.bundle/pr.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ri.svg -e ../../StateFlags.bundle/ri@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ri.svg -e ../../StateFlags.bundle/ri.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f sc.svg -e ../../StateFlags.bundle/sc@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f sc.svg -e ../../StateFlags.bundle/sc.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f sd.svg -e ../../StateFlags.bundle/sd@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f sd.svg -e ../../StateFlags.bundle/sd.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f tn.svg -e ../../StateFlags.bundle/tn@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f tn.svg -e ../../StateFlags.bundle/tn.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f tx.svg -e ../../StateFlags.bundle/tx@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f tx.svg -e ../../StateFlags.bundle/tx.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ut.svg -e ../../StateFlags.bundle/ut@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f ut.svg -e ../../StateFlags.bundle/ut.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f va.svg -e ../../StateFlags.bundle/va@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f va.svg -e ../../StateFlags.bundle/va.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f vt.svg -e ../../StateFlags.bundle/vt@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f vt.svg -e ../../StateFlags.bundle/vt.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wa.svg -e ../../StateFlags.bundle/wa@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wa.svg -e ../../StateFlags.bundle/wa.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wi.svg -e ../../StateFlags.bundle/wi@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wi.svg -e ../../StateFlags.bundle/wi.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wv.svg -e ../../StateFlags.bundle/wv@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wv.svg -e ../../StateFlags.bundle/wv.png  -w 64 -h 43
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wy.svg -e ../../StateFlags.bundle/wy@2x.png  -w 128 -h 85
/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f wy.svg -e ../../StateFlags.bundle/wy.png  -w 64 -h 43